services:
  - type: web
    name: quizbywin
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py createsuperuser --noinput || true
    startCommand: gunicorn quiz_manager.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quiz_manager.settings
      - key: PYTHON_VERSION
        value: 3.11
